### ISSUE TITLE
Change default values for FY2017

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/ffvtr#33]
Reset FY17 Tuition & Fee Revenue to be $135m (instead of $131m); state approps amount should be $325

**Comment by brucecrevensten** [comment]
Requesting more clarification; we calculate that as a derived number so what we really need to know here is the actual Tuition & Fees amount for 2017.  Otherwise we're guessing, since many values could result in a total of 135m$.

**Comment by cstephen** [comment]
We need to know "Student FTE" for 2017, also. We've updated Total State Appropriation to $325m in #39, but we're still using 2016 values for 2017 for both:

- Student FTE
- Tuition & Fees per Student FTE ($)

**Comment by brucecrevensten** [comment]
2017 values in the table should be the following:
Total Tuition & Fees (Million $) - 135
Student FTE - 19,229
Tuition & Fees per Student - 7,020

2018
Total Tuition & Fees (Million $) - 135
Student FTE - 18,652
Tuition & Fees per Student - whatever 135,000,000 divided by 18,652
